CREATE TABLE IF NOT EXISTS `proyecto_urban_rutas` (
  `PROYECTO_URBAN_RUTA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre_Ruta` varchar(100) NOT NULL,
  `Tipo` varchar(50) NOT NULL,
  PRIMARY KEY (`PROYECTO_URBAN_RUTA_ID`),
  KEY `PROYECTO_URBAN_RUTA_ID` (`PROYECTO_URBAN_RUTA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;