CREATE TABLE IF NOT EXISTS `proyecto_urban_rutas_paradas` (
  `PROYECTO_URBAN_RUTAS_PARADA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(50) NOT NULL,
  PRIMARY KEY (`PROYECTO_URBAN_RUTAS_PARADA_ID`),
  KEY `PROYECTO_URBAN_RUTAS_PARADA_ID` (`PROYECTO_URBAN_RUTAS_PARADA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;