CREATE TABLE IF NOT EXISTS `proyecto_urban_rutas_puntos` (
  `PROYECTO_URBAN_RUTAS_PUNTO_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Latitud` float NOT NULL,
  `Longitud` float NOT NULL,
  PRIMARY KEY (`PROYECTO_URBAN_RUTAS_PUNTO_ID`),
  KEY `PROYECTO_URBAN_RUTAS_PUNTO_ID` (`PROYECTO_URBAN_RUTAS_PUNTO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;